services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: casados_dev
      POSTGRES_PASSWORD: pgpass
    volumes:
      - ./.data:/var/lib/postgresql/data
  redis:
    image: "redis:4.0.14-alpine"
    command: redis-server
    ports:
     - 6381:6379
