default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: casados_dev
  username: postgres
  password: pgpass
  host: 127.0.0.1
  port: 5432

test:
  <<: *default
  database: casados_test
  username: postgres
  password: pgpass
  host: 127.0.0.1
  port: 5432

production:
  <<: *default
  database: casados_api_production
  username: casados_api
  password: <%= ENV["CASADOS_API_DATABASE_PASSWORD"] %>
